### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by Ango87** [ca333/rng-scanner#3]
Please help i get error

**Comment by Ango87** [comment]
![Uploading Screenshot_20211227_224443_com.termux.jpg…]()

**Comment by 0xStormbit** [comment]
How do I get Transaction ID of this output 
"Bitcoin Handle : 1GQdrgqAbkeEPUef1UpiTc4X1mUHMcyuGW
In Enter NR : 141 ~ 220020a271a0897f1b7a7f0db9acb517ae2b6d53dda3833808d02c6a1cc21dc1a68680
Resued R-Worth : a0s97f1b7a7f0db9acb517ae2b6d53dda3833808d02c6a1cc21dc1a686544"

**Comment by Ango87** [comment]
@stateactor please help me i can't get the reused r value because this problem

**Comment by Ango87** [comment]
@stateactor I have already used your program but I get this error every time Please edit the code


blink@localhost:~$ cd Bitcoin-Key-Compression-Toolblink@localhost:~/Bitcoin-Key-Compression-Tool$ lsR-Scaner.py   START.bat     r-s-z-to-wif.py       README.md     keyUtils.py   txnUtils.py
RawTX_RSZ.py  keyUtils.pyc  txnUtils.pyc
blink@localhost:~/Bitcoin-Key-Compression-Tool$ python2 R-Scaner.py
SCAN ADDR
type address:  
(I already type the address) 
ADDRESS-R-SCAN:                                   Traceback (most recent call last):
  File "R-Scaner.py", line 72, in <module>
    rscan(addr)
  File "R-Scaner.py", line 15, in rscan               addrdata = json.load(urllib2.urlopen(urladdr % (addr, '0')))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1248, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1202, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1116, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python2.7/httplib.py", line 942, in putrequest
    self._validate_path(url)
  File "/usr/lib/python2.7/httplib.py", line 1032, in _validate_path
    raise InvalidURL(msg)
httplib.InvalidURL: URL can't contain control characters. '/address/here is the address ?format=json&offset=0' (found at least ' ')

**Comment by 0xStormbit** [comment]
Ok

**Comment by juniorcines** [comment]
Here I leave the improved version> https://github.com/juniorcines/rng-scanner-by-juniorcines

**Comment by aesthetic28** [comment]
> Here I leave the improved version> https://github.com/juniorcines/rng-scanner-by-juniorcines

where??no link code 404

**Comment by 0xStormbit** [comment]
Paid tool. $50 btc
